import { StyleSheet } from "react-native";
import colors from './colors.js'

const styles = StyleSheet.create({
    container:{
        flex:1,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:colors.Background
    },
    headerContainer:{
        display:'flex',
        backgroundColor:colors.containerBackground,
        borderRadius:10,
        margin:15,
        padding:15,
        width:'100%'
    },
    headerText:{
        fontSize:36,
        color:'#fff'
    },
    flatBox:{
        justifyContent:'flex-start',
        alignItems:'center',
        fontSize:20,
        color:'#fff',
        width:'100%',
        borderRadius:10
    },
    flatContainer:{
        flex:1,
        flexDirection:'row',
        backgroundColor:colors.containerBackground,
        width:'100%',
        borderRadius:10,
        padding:20,
        paddingHorizontal:60,
        marginBottom:15,
        marginTop:15
    },
    body:{
        width:'100%',
        backgroundColor:colors.containerBackground,
        margin:15,
        padding:15,
        display:'flex',
        borderRadius:10
    },
    iconContainer:{
        display:'flex',
    },
    icon:{
        color:'#fff',
        justifyContent:'center'
    },
    add:{
        margin:15,
        justifyContent:'center',
        alignItems:'center'
    },
    input:{
        width:'100%',
        backgroundColor:colors.containerBackground,
        borderRadius:10,
        margin:10,
        padding:10,
        fontSize:18
    },
    btn:{
        width:'100%',
        borderRadius:10,
        backgroundColor:colors.containerBackground,
        margin:10,
        padding:10,
        justifyContent:'center',
        alignItems:'center'
    },
    txtBtn:{
        color:'#fff',
        fontSize:20
    },
    rmv:{
        padding:20,
        margin:15,
        justifyContent:'flex-end',
        alignItems:'flex-end'
    },
    flatName:{
        margin:10,
        justifyContent:'flex-start',
        alignItems:'flex-start'
    },
    flatOverall:{
        flexDirection:'row'
    },
})

export default styles;